
from etl import ler_csv,filtrar_produtos_nao_entregues,somar_valores_dos_produtos_filtrados

path_arquivo="vendas.csv"
lista_de_produtos=ler_csv(path_arquivo)
print(lista_de_produtos)
produtos_entregues= filtrar_produtos_nao_entregues(lista_de_produtos)
valor_dos_produtos_entregues= somar_valores_dos_produtos_filtrados(produtos_entregues)
print(valor_dos_produtos_entregues)